name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build in ${{ matrix.build-type }} mode
        run: cargo build --${{ matrix.build-type }}

      - name: Build normal mode
        run: cargo build
